language: node_js
node_js:
  -"8.10.0"
dist: trusty # needs UbuntuTrusty
sudo:false  #no need for virtualization.
addons:
  chrome: stable # have Travis install chrome stable.
cache:
  directories:
    - node_modules
install:
  - npm
script:
  - npm run test